version: '3'
services:
  jenkins:
    user: root
    image: jenkins/docker
    build:
      context: /root/repository-git/dockerjenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - net
networks:
  net:
